config/routes.rb
Rails.application.routes.draw do
  get 'stores', to: 'pages#stores'
  get '/show/:id', to: 'pages#show', as: "show_stores"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{address}, #{city}, #{postcode}, #{state},#{country}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def stores
    @stores = Store.all
  end

  def show
    @stores = Store.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<h1> Your selected Store </h1>
<strong><%= @stores.title %><strong>
<%= @stores.full_address %><hr>

<p>
  <strong>latitude, longitude</strong>
  <%= @stores.longitude %> <%= @stores.latitude %></p>

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBHFYq011AJfrl4K9weE5YKF7Z_u7pfquQ
    &q= <%= @stores.full_address %> "allowfullscreen>
</iframe>

<hr>

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/streetview?key=AIzaSyBKC3MKvHAjWxX3MdvW207chlbMEyUWapE
    &location= <%= @stores.latitude %>,<%= @stores.longitude %>
    &heading=210&pitch=10&fov=35" allowfullscreen>
</iframe>

app/views/pages/stores.html.erb
<h1>Stores</h1>

<br>
<% @stores.each do |store| %>
  <%= link_to "#{store.title}", show_stores_path(store)%>
  <%= store.full_address %>
  <br><hr>
<% end %>